/*
    IDPS PROGRAM MODULE -- CLIENT API
    ---------------------------------

    CREDITS
    Copyright (c) 2001-2004, Jean-Francois Rabasse
    Contact info  <info@idps.org>
    --
    This software is free software, see the file LICENSE for details.
    This software comes with  NO WARRANTY,  use it at your own risks.

    DESCRIPTION
    IDPS client application API.

    WARNING: this file is generated by software.
    Do not edit, modifications would be lost !

    GENERATED: 2006/06/13 22:53 UTC
*/

#ifndef LIBIDPS_H

// TEMPORANEAMENTE!
#ifndef HAVE_IDPS
#warning "Stiamo facendo il debug senza idps!"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* SYMBOLIC PARAMETERS */
/* ------------------- */
/* Warning: numeric values are subject to changes. */
/* Always use the defined symbols. */

/* GLOBAL CONSTANTS */
#define IDPS_VERSION         3
#define IDPS_RELEASE         2
#define IDPS_PORTNUM         3797

/* PLOT STYLE VALUES */
#define PLOTSTYLE_LINE       0
#define PLOTSTYLE_PIXEL      38
#define PLOTSTYLE_CIRCLE     33
#define PLOTSTYLE_SQUARE     34
#define PLOTSTYLE_CROSS      35
#define PLOTSTYLE_DIAMOND    36
#define PLOTSTYLE_TRIANGLE   37
#define PLOTSTYLE_CROSSHAIR  39
#define PLOTSTYLE_CUSTOM     48

/* LINE STYLE VALUES (when Plot Style is LINE) */
#define LINESTYLE_SOLID      0
#define LINESTYLE_DOT        17
#define LINESTYLE_DASH       18
#define LINESTYLE_DASHDOT    19

/* MARKERS TYPES */
#define AXISMARK_X           0
#define AXISMARK_Y           1
#define AXISMARK_XY          2

/* RASTER DATA PACKING MODES */
#define DATAPACK_UNS         1
#define DATAPACK_MAX         2
#define DATAPACK_MIN         3
#define DATAPACK_AVG         4
#define DATAPACK_SUM         5

/* LOOKUP TABLES SPREAD MODES */
#define LUTSPREAD_USR        0
#define LUTSPREAD_LIN        1
#define LUTSPREAD_LOG        2
#define LUTSPREAD_UNI        3
#define LUTSPREAD_ISO        4

/*
 * CLIENT CONNECTIONS MANAGEMENT
 * -----------------------------
 */
int idpsCreate(int mark);
int idpsSelect(int mark);
int idpsDelete(int mark);

/*
 * SERVER CONNECTION & STATUS
 * --------------------------
 */
int idpsConnect(const char* host, int port);
int idpsStatus(void);
int idpsMessage(int code, char* text, unsigned text_size);

/*
 * SERVER CONTROL
 * --------------
 */
int idpsCheck(void);
int idpsClose(void);
int idpsSigEnable(int mode);

/*
 * MAIN DIALOG FUNCTIONS
 * ---------------------
 */
int idpsSetCaption(const char* strn);
int idpsGetCaption(char* strn, unsigned strn_size);
int idpsSaveMetaFile(const char* path);
int idpsLoadMetaFile(const char* path);

/*
 * CANVAS FUNCTIONS
 * ----------------
 */
int idpsSetSize(unsigned width, unsigned height);
int idpsErase(void);
int idpsAutoUpdate(unsigned mode);
int idpsUpdate(void);

int idpsNewViewPort(const char* title, const char* xlabel, const char* ylabel);
int idpsSelViewPort(unsigned port);
int idpsGetViewPort(unsigned* port);

/*
 * DATA MANAGEMENT
 * ---------------
 */
int idpsGetLastPort(unsigned* port);
int idpsGetLastData(unsigned* data);
int idpsGetLastMarker(unsigned* mark);
int idpsDeleteObject(unsigned onum);

/*
 * VIEWPORTS FUNCTIONS
 * -------------------
 */
int idpsClear(unsigned port);
int idpsAutoScale(unsigned port);
int idpsXRange(unsigned port, float mini, float maxi);
int idpsYRange(unsigned port, float mini, float maxi);
int idpsAxisMarker(unsigned port, unsigned type, float xpos, float ypos, const char* text);

int idpsTitle(unsigned port, const char* text);
int idpsXLabel(unsigned port, const char* text);
int idpsYLabel(unsigned port, const char* text);
int idpsDefGridMode(unsigned mode);
int idpsGridMode(unsigned port, unsigned mode);
int idpsDefXLogMode(unsigned mode);
int idpsXLogMode(unsigned port, unsigned mode);
int idpsDefYLogMode(unsigned mode);
int idpsYLogMode(unsigned port, unsigned mode);
int idpsDefXRevMode(unsigned mode);
int idpsXRevMode(unsigned port, unsigned mode);
int idpsDefYRevMode(unsigned mode);
int idpsYRevMode(unsigned port, unsigned mode);
int idpsColSpan(unsigned port, unsigned span);

/*
 * DATA PLOTS FUNCTIONS
 * --------------------
 */
int idpsPolyLine(unsigned port, unsigned count, const float* pX, const float* pY);
int idpsSpectrum(unsigned port, float xmini, float xstep, unsigned count, const float* pS);
int idpsIntSpectrum(unsigned port, float xmini, float xstep, unsigned count, const int* pS);

/*
 * RASTER DATA FUNCTIONS
 * ---------------------
 */
int idpsRasterMap(unsigned port, float xbase, float xstep, float ybase, float ystep, unsigned xsize, unsigned ysize, const float* data);
int idpsDefColorPalette(unsigned ncol, const float* defs);
int idpsColorPalette(unsigned port, unsigned ncol, const float* defs);
int idpsLookupTable(unsigned port, unsigned slots, const float* values);
int idpsLookupSpread(unsigned port, unsigned size, unsigned mode, float mini, float maxi);

/*
 * DATA ATTRIBUTES FUNCTIONS
 * -------------------------
 */
int idpsDefMarkColor(float red, float green, float blue);
int idpsDefPlotColor(float red, float green, float blue);
int idpsPlotColor(unsigned data, float red, float green, float blue);
int idpsPlotLabel(unsigned data, const char* name, const char* format);
int idpsDefPlotStyle(unsigned style);
int idpsPlotStyle(unsigned data, unsigned style);
int idpsDefLineStyle(unsigned style);
int idpsLineStyle(unsigned data, unsigned style);
int idpsDefMarkStep(int step);
int idpsMarkStep(unsigned data, int step);
int idpsDefMarkSize(int size);
int idpsMarkSize(unsigned data, int size);
int idpsDefPlotMark(int mark, const char* text);
int idpsDefDataPack(int mode);
int idpsDataPack(unsigned data, int mode);

#ifdef __cplusplus
}
#endif
#define LIBIDPS_H
#endif /* LIBIDPS_H */
